// <auto-generated />
namespace ParentControl.Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewSessionScheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewSessionScheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201707061937599_NewSessionScheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
